### ISSUE TITLE
Request: One use items

### ISSUE THREAD

**Issue by SirWindfield** [MoreThanHidden/RestrictedPortals#17]
It would be awesome if it was possible to make the items one use only and remove them afterwards from the inventory. I might implement this later on myself. I don't think this would be too complicated tbh.

**Comment by SirWindfield** [comment]
@MoreThanHidden Wouldn't the problem be solved by appending a NBT tag to the item holding the players name that crafted it? And when trying to enter the dimension check against the players own name. If it has the same name, let him into the dimension. If not, prevent it. That would solve the 'other player crafts the item' problem I guess.

**Comment by MoreThanHidden** [comment]
Yeah just complicates things unnecessarily, will implement as a config option.
"Consume item rather than craft" default will be false and "Consumable Portal Block Whitelist" default will be "minecraft:portal,minecraft:end_portal"

Would recommend changing the blocked message to **"Please use a %item% on a Portal to unlock the %dim%"** rather than the default **"Please craft a %item% to enter the %dim%"**
