### ISSUE TITLE
1.16.3 Reload Datapack Issues

### ISSUE THREAD

**Issue by BedrockLegends** [MoreThanHidden/RestrictedPortals#28]
Your mod seems to be causing Custom Datapacks to load first and not last. Example we have a custom mod that ships with a custom Datapack with recipes and when we load a modpack with this mod and ours it Loads them both first before any other mods and cause our mod not to work or load right

**Comment by MoreThanHidden** [comment]
Alright will take a look tomorrow, need to force the custom data packs to load after the world otherwise causes issues as this mod generates a datapack based on the config, I'll look at limiting it to this single data pack. But I'm only doing the same as /reload so I would also check if that causes the same issue.

**Comment by BedrockLegends** [comment]
its kinda and odd thing
![2020-10-04_12 50 04](https://user-images.githubusercontent.com/48525410/95023005-28603780-0640-11eb-8751-7a61d327cbc7.png)

**Comment by BedrockLegends** [comment]
right now u can see yours is loading at the top and mines at the bottom cause the mod author for said mod got it to load, but still think its a issue as yours is at the top and I think yours should be loading first

**Comment by MoreThanHidden** [comment]
Fixed in 1.16.4-1.1.7
